services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia  # use NVIDIA runtime to ensure GPU access
            capabilities: ["gpu"]
            count: all  # adjust count for the number of GPUs you want to use

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "vidsage_tscripts"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dbpass"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - published: 8080
        target: 8080
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  elasticsearch-data:
  ollama:
  postgres_data: